config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { confirmations: 'confirmations' }

  root 'home#index'

  resources :users do
    resources :bio, only: [:edit]
  end

  resources :games do
    resources :signups, only: [:create, :destroy]
    resources :requests, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :donate
  resources :about
  resources :comments
  resources :map, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :games, only: [:index, :new, :create, :show, :destroy]
      resources :users
      resources :comments, only: [:index, :new, :create]
      resources :nearmegames
    end
  end

  resources :conversations do
    resources :messages
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :games, through: :signups
  has_many :comments
  has_many :requests
  has_many :signups
  has_one :profile

  geocoded_by :current_sign_in_ip,
    :latitude => :lat, :longitude => :lng
  after_validation :geocode, :if => :current_sign_in_ip_changed?

  validates :first_name, presence: true
  validates :last_name, presence: true

  validates :email, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == "admin"
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController

  def index
    @current_user = current_user
    render json: @current_user
  end

  def create
    @user = User.create(user_params)
    if @user.save!
      render json: @user
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Successfully deleted user!"
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    if user_signed_in?
    @user = current_user
    else
      flash[:notice] = 'Please sign in first'
      redirect_to new_user_session_path
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.email = params[:user][:email]
    # @user.avatar_url = params[:user][:avatar_url]
    @user.bio = params[:user][:bio]

    if @user.save
      flash[:notice] = 'Success! Your profile has been updated.'
      redirect_to @user
    else
      @user.email = params[:user][:email]
      # @user.avatar_url = params[:user][:avatar_url]
      @user.bio = params[:user][:bio]
      render :edit
    end
  end

  def destroy
    this_user = User.find(params[:id])
    this_user.destroy
    redirect_to root_path
  end
end

app/views/users/edit.html.erb
<div class='bumper-25'></div>
  <h2 class='text-center'>Edit Your Profile</h2>
<div class='bumper-25'></div>

<section>
  <%= form_for(@user, html: {class: 'form--signup__box'}) do |f| %>

  <div class="form--signup__field">
    <%= f.label :email, "Email" %>
    <%= f.email_field :email, autofocus: true, :input_html => { :value => @user.email } %>
  </div>

  <div class="form--signup__field">
    <%= f.label :bio, "What do you want others to know about you? Add a bio here." %>
    <%= f.text_field :bio %>
  </div>

  <div class='bumper-25'></div>

  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error| %>
      <p><%= error %></p>
    <% end %>
    <div class='bumper-25'></div>
  <% end %>

  <div class="form--signup__submit-container">
    <%= f.submit "Update Profile", class: 'btn' %>
  </div>

  <% end %>

</section>

app/views/users/show.html.erb
<div class='row'>
  <div class='columns small-12 small-centered text-center'>
    <h1><%= @user.username %>'s Profile Page:</h1>
  </div>
</div>

<!-- <div id='background' class='small-12 columns medium-8 columns float-left'>
  <div class='small-12 columns'>
    <div class='medium-9 columns'>
      <h1><%= @user.username %>'s Profile Page:</h1>
    </div>
  </div> -->

<div class='row'>
  <div class='columns small-12 text-center'>
    <h2>Your Games:</h2>
    <% @user.signups.each do |signup| %>
      <% if (signup.game.date > Time.zone.now + 1.day) %>
        <%= link_to signup.game.title, game_path(signup.game) %>
          <% if signup.game.creator == @user.id %>
            Creator
          <% end %>
      <% end %>
      <br />
    <% end %>
  </div>
</div>

<!-- <h2>Your Games:</h2>
  <% @user.signups.each do |signup| %>
    <% if (signup.game.date > Time.zone.now + 1.day) %>
      <%= link_to signup.game.title, game_path(signup.game) %>
        <% if signup.game.creator == @user.id %>
          Creator
        <% end %>
        <% end %>
    <br />
  <% end %>
  <hr /> -->

<div class='row'>
  <div class='columns small-12 text-center'>
    <h2>Your Requests:</h2>
    <% if @user.requests.empty? %>
      No requests made
    <% else %>
    <% @user.requests.each do |request| %>
      <p>
        <div class='small-9 columns'><%= link_to request.game.title, game_path(request.game) %></div>
        <%= button_to 'Cancel Request', game_request_path(request.game, request), method: :delete, id: 'special' %>
      </p>
      <% end %>
    <% end %>
    <hr />
  </div>
</div>

<!-- <h2>Your Requests:</h2>
  <% if @user.requests.empty?%>
    No requests made.
  <% end %>
  <% @user.requests.each do |request| %>
    <p>
      <div class='small-9 columns'><%= link_to request.game.title, game_path(request.game) %></div>
      <%= button_to 'Cancel Request', game_request_path(request.game, request), method: :delete, id: 'special' %>
    </p>
  <% end %>
  <hr />
</div> -->

<div class='row'>
  <div class='columns small-12 text-center'>
    <h2 class='text-center'>About Me</h2>
    <div class='bumper-25'></div>
    <% if @user.bio.nil?%>
      <p class='text-center'>This user does not have a bio yet</p>
    <% else %>
      <p class='text-center'><%= @user.bio %></p>
    <% end %>
    <% if current_user.id == @user.id %>
      <div class='text-center'>
        <div class='bumper-25'></div>
        <%= link_to 'Edit Profile', edit_user_path(@user), method: :get, class: 'btn' %>
      </div>
    <% end %>
  </div>
</div>

<!-- <div class='medium-4 columns float-right'>
  <div id='background' class='medium-11 columns float-right'>
    <%= button_to 'Create New Game', new_game_path, method: :get, id: 'button' %>
  </div>
</div> -->


<!-- <div>
  <h1> About Me </h1>
  <% if @user.bio.nil?%>
   This user does not have a bio yet.
  <% else %>
  <%= @user.bio %>
  <% end %>
  <div class='medium-3 columns'>
    <%= button_to 'Edit Profile', edit_user_path(@user), method: :get, id: 'button' %>
  </div>
</div> -->

<div class='bumper-50'></div>
<div class='bumper-50'></div>

<div class='row'>
  <div class='columns small-12 text-center'>
    <%= link_to "Cancel my account", registration_path(current_user), data: { confirm: "Are you sure that you want to delete your account?" }, method: :delete, class: 'btn' %>
  </div>
</div>