config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { confirmations: 'confirmations' }

  root 'home#index'

  resources :users do
    resources :bio, only: [:edit]
  end

  resources :games do
    resources :signups, only: [:create, :destroy]
    resources :requests, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :donate
  resources :about
  resources :comments
  resources :map, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :games, only: [:index, :new, :create, :show, :destroy]
      resources :users
      resources :comments, only: [:index, :new, :create]
      resources :nearmegames
    end
  end

  resources :conversations do
    resources :messages
  end

end

app/models/game.rb
class Game < ApplicationRecord

  has_many :users, through: :signups
  has_many :comments
  has_many :signups
  has_many :requests

  validates :title, presence: true
  validates :gametype, presence: true
  validates :time, presence: true
  validates :date, presence: true
  validates :address, presence: true
  validates :number_of_players, presence: true
  validates :creator, presence: true, numericality: true


  geocoded_by :address, :latitude  => :lat, :longitude => :lng
  after_validation :geocode, if: :address_changed?


# def address
#   [address, city, zip].compact.join(', ')
# end

# def full_address
#    full_address = "#{self.address + self.city + self.zip}"
# end

def self.search(search)
  if search
      where("title ILIKE ? OR gametype ILIKE ? OR address ILIKE ? OR time ILIKE ? OR date ILIKE ? OR number_of_players ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%").order('date ASC')
    else
      order('date ASC')
    end
  end

end

app/controllers/api/v1/games_controller.rb
class Api::V1::GamesController < Api::V1::BaseController

  def index
    recentgames = Game.order(created_at: :desc).limit(5)
    render json: recentgames
  end

  def show
    game = Game.find(params[:id])
    render json: game, user: current_user
  end

  def create
    body = request.body.read
    parsed = JSON.parse(body)
    game = Game.new(parsed)

    if game.save!
      render json: game
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.search(params[:search])
    @user = current_user
  end

  def show
    @current_user = current_user
    authenticate_user!
    @game = Game.find(params[:id])
    @request = Request.new
    @signup = Signup.new
  end

  def new
    if user_signed_in?
      @game = Game.new
    else
      flash[:notice] = 'Please sign in to add a game'
      redirect_to new_user_session_path
    end
  end

  def create
    if user_signed_in?
      @game = Game.create(game_params)
      require_relative 'httprequest.rb'
      if @game.address.include?(' ') && !@game.address.include?('.')
        require_relative 'httprequest.rb'
        results = Httprequest.call(@game.address)
        @game.lat = results[0]
        @game.lng = results[1]
      end

      if @game.save
        flash[:notice] = 'Thank you for adding this listing to our database!'
        Signup.create(user: current_user, game: @game)
        redirect_to game_path(@game)
      else
        flash[:notice] = @game.errors.full_messages.to_sentence
        redirect_back(fallback_location: root_path)
      end
    else
      flash[:alert] = 'Please sign in to add a game'
      redirect_to new_user_session_path
    end
  end

  def edit
    if user_signed_in?
      @game = Game.find(params[:id])
      unless current_user.id == @game.creator
        flash[:alert] = "UNAUTHORIZED"
        redirect_back(fallback_location: root_path)
      end
    else
      flash[:alert] = "UNAUTHORIZED"
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    @game = Game.find(params[:id])
    @game.update_attributes(game_params)
    if @game.address.include?(' ') && !@game.address.include?('.')
      require_relative 'httprequest.rb'
      results = Httprequest.call(@game.address)
      @game.lat = results[0]
      @game.lng = results[1]
    end
    if @game.save
      flash[:notice] = "Thank you for editing this listing!"
      redirect_to game_path(@game)
    else
      flash[:notice] = @game.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @game = Game.find(params[:id])
    if user_signed_in? && (current_user.id == @game.creator)
      Comment.where(game: @game).delete_all
      Signup.where(game: @game).delete_all
      Request.where(game: @game).delete_all
      @game.delete
      flash[:alert] = "You have deleted this game listing successfully"
      redirect_to games_path
    else
      flash[:alert] = 'UNAUTHORIZED'
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def game_params
    params.require(:game).permit(
    :title,
    :gametype,
    :time,
    :date,
    :address,
    :number_of_players,
    :latitude,
    :longitude,
    :creator,
    :username
  )

  end
end

app/views/games/_form.html.erb
<div class='bumper-25'></div>
  <h1 class='text-center'>Create New Game Listing</h1>
<div class='bumper-25'></div>

<section>
  <%= form_for(@game, html: {class: 'form--newgame__box'}) do |f| %>

  <div class="form--signup__field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form--signup__field">
    <%= f.label :number_of_players, value: 'How many players?' %>
    <%= f.number_field :number_of_players, default_value: '2' %>
  </div>

  <%= f.hidden_field :creator, value: current_user.id %>

  <div class="form--signup__field">
    <%= f.label :gametype, value: 'Gametype' %>
    <%= f.select :gametype, [['Standard','Standard'], ['Modern', 'Modern'], ['EDH', 'EDH'], ['Frontier', 'Frontier'], ['Limited / Draft', 'Limited / Draft'], ['Vintage', 'Vintage'], ['Legacy','Legacy'], ['Pauper', 'Pauper']], {}, {onchange: "showfield(this.options[this.selectedIndex].value)"} %>
  </div>

  <div class="form--signup__field">
    <%= f.label :time %>
    <%= f.time_field :time %>
  </div>

  <div class="form--signup__field">
    <%= f.label :date, value: 'Please choose a date at a maximum of 2 weeks from today.'%>
    <%= f.date_field :date, min: Date.today, max: Date.today + 2.week, :value => Time.now.strftime('%Y-%m-%d') %>
  </div>

  <div class="form--signup__field">
    <%= f.label :address, value: 'Please supply a full valid address to be added to the map.' %>
    <%= f.text_field :address %>
  </div>

  <div class="form--signup__field text-center">
    <%= f.submit "Create Game", class: 'btn' %>
    <%= button_to 'Cancel', map_index_path, class: 'btn' %>
  </div>

  <% end %>

</section>

app/views/games/edit.html.erb
<div id='background'>
  <h1>Edit Game Listing</h1>

    <%= render 'form' %>

  <%= button_to 'Delete Game', game_path(@game), method: :delete, data: { confirm: "Are you sure? This action cannot be undone." }, id: 'special' %>
  <%= link_to 'Cancel', game_path %>
</div>

app/views/games/index.html.erb
<div class='row'>
  <div class='columns small-12 text-center'>
    <h1> Your Search Results</h1>
  </div>
</div>

<div class='row'>
  <div class='columns small-12'>
    <% @games.each do |game| %>
      <% if (game.date > Time.zone.now + 1.day) %>
        <h3> <%= link_to game.title, game_path(game) %> </h3>
        <h5> <span class='search-result-bold'>What:</span> <%= game.gametype %> </h5>
        <h5> <span class='search-result-bold'>Where:</span> <%= game.address %> </h5>
        <h5> <span class='search-result-bold'>When:</span> <%= game.date %>, <%= game.time %> </h5>
        <h5> <span class='search-result-bold'>Players:</span> <%= game.number_of_players %> </h5>
      <% end %>
    <% end %>
    <hr />
  </div>
</div>

<!-- <div id='background' class='large-offset-1 columns medium-offset-1 columns small-offset-1 columns large-10 columns medium-10 columns small-10 columns'>
<h1> Your Search Results</h1>
  <% @games.each do |game| %>
    <p>
      <% if (game.date > Time.zone.now + 1.day) %>
        <u><%= link_to game.title, game_path(game) %></u>:
        <br />What: <%= game.gametype %>
        <br />Where: <%= game.address %> // When: <%= game.date %>, <%= game.time %>
        // Players: <%= game.number_of_players %>
        <% end %>
      <% end %>
      <hr />
    </p>
</div>

<div id="app"></div>

<div class='small-12 columns medium-12 columns large-12 columns' id='newgame'>
  <div class='large-4 medium-6 small-8'>
    <%= button_to 'Add a Game Listing', new_game_path, method: :get, id: 'button'  %>
  </div>
</div> -->

app/views/games/new.html.erb
<div class='large-12 columns medium-12 columns small-12 columns'>
  <%= render 'form' %>
</div>

app/views/games/show.html.erb
<div class='bumper-25'></div>
  <div class='row'>
    <div class='columns small-12 text-center'>
      <h1><%= @game.title %></h1>
      <br width='50%' />
    </div>
  </div>
<div class='bumper-25'></div>

<div class='row'>
  <!-- MAP -->
  <div class='columns small-12 medium-6 text-center'>
    <div id="map" style='width: 100%; height: 400px;'></div>
    <br />
    <div>
      <%= form_for [@game, @request] do |f| %>
        <%= f.text_field :body, placeholder: "Please tell us why you'd like to join", id: 'field' %>
        <%= f.submit value:'Request to Join', class: 'button' %>
      <% end %>
    </div>
    <% if (Request.where(user: current_user, game: @game) != []) %>
      <div class='large-4 columns medium-2 columns small-6 columns float-right'>
        <% @request = Request.where(user: current_user, game: @game).first %>
        <%= button_to 'Delete Request', game_request_path(@game, @request), method: :delete, data: { confirm: "Are you sure?" }, class: 'button' %>
      </div>
    <% end %>
  </div>
  <!-- GAME INFO -->
  <div class='columns small-12 medium-6 text-center'>
    <h3>Game Info</h3>
    <p>Type: <%= @game.gametype %></p>
    <p>Time: <%= DateTime.parse(@game.time).strftime("%l:%M%p") %></p>
    <p>Date: <%= @game.date %></p>
    <p>Location: <%= @game.address %></p>
    <p>Max Total Players: <%= @game.number_of_players %></p>
    <!-- LOGIC TO GET REMAINING SPOTS AVAILABLE FOR THIS GAME -->
    <% @spots_left = @game.number_of_players.to_i - @game.signups.size %>
    <p>Spots Left: <%= @spots_left %></p>
    <p>Creator: <%= link_to User.find(@game.creator).username, user_path(@game.creator) %></p>
    <h1> Players: </h1>
    <% @game.signups.each do |signup| %>
      <%= link_to signup.user.username, user_path(signup.user) %>
      <% if current_user == signup.user && current_user.id != @game.creator %>
        <%= button_to 'Leave Game', game_signup_path(@game, signup), data: {confirm: "Are you sure you want to leave this game?"},  method: :delete, class: 'button text-center' %>
      <% elsif current_user.id == @game.creator %>
        <%= button_to 'Remove Player', game_signup_path(@game, signup), method: :delete, class: 'button text-center' %>
      <% end %>
    <% end %>
  </div>
</div>

<hr width='50%'/>

<% if current_user.id == @game.creator %>
  <div class='row'>
    <div class='columns small-12 medium-6 text-center'>
      <h1>Game Requests</h1>
      <% if @game.requests.size < 1 %>
        <p class='text-center'> No new requests </p>
      <% else %>
        <% @game.requests.each do |request| %>
          <p><span class='search-result-bold'><%= request.user.username %></span>: <%= request.body %></p>
          <%= form_for [@game, @signup] do |f| %>
            <%= f.hidden_field :user_id, value: request.user.id %>
            <%= f.submit(value="Add Player", class: 'button') %>
          <% end %>
          <%= button_to 'Deny', game_request_path(@game, request), method: :delete, class: 'button' %>
        <% end %>
      <% end %>
    </div>
    <div class='columns small-12 medium-6 text-center'>
      <% if current_user.id == @game.creator %>
        <h1>Add Player to Game Manually:</h1>
        <%= form_for [@game, @signup] do |f| %>
          <%= f.label :user, value: 'Username of Player:' %>
          <%= f.text_field :user %>
          <br />
          <%= f.submit(value='Add Player', class: 'button') %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class='row'>
    <% if @current_user.games.size > 0 %>
    <hr width='50%'/>
    <div class='columns small-12'>
      <h3 class='text-center'>Your Games</h3>
      <% current_user.games.each do |game| %>
        <% if (game.date > Time.zone.now + 1.day) %>
          <p><span class='search-result-bold'><%= link_to game.title, game_path(game.id) %></span></p>
          <% if @game.creator == current_user.id %>
            <p><span class='search-result-bold'>Role:</span> Host</p>
          <% else %>
            <p><span class='search-result-bold'>Role:</span>Player</p>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <% else %>
      <div class='columns small-12 text-center'>
        <p>You have no games!</p>
      </div>
    <% end %>
  </div>
  <div class='row'>
    <div class='columns small-12 text-center'>
      <% if (current_user.id == @game.creator) %>
        <%= link_to 'Edit Current Game', edit_game_path(@game), id: 'button', class: 'text-center' %>
      <% end %>
    </div>
  </div>
<% end %>

<div class='bumper-50'></div>
<div class='bumper-50'></div>





<!-- <div id='background' class='small-12 columns medium-8 columns large-8 columns'>
  <div class='large-12 columns medium-12 columns small-12 columns'>

    <h1>
      <%= @game.title %>
    </h1>
  </div> -->

  <!-- <div id="map" class='' style='width: 100%; height: 400px; '></div>

  <p>We are playing <%= @game.gametype %>:
    <%= @game.date %> at <%= DateTime.parse(@game.time).strftime("%l:%M%p") %> at <%= @game.address %></p>
  <p>Description: <%= @game.title %></p>
  <p>Game run by: <%= link_to User.find(@game.creator).username, user_path(@game.creator)  %></p> -->
  <!-- <p>Player Total: <%= @game.number_of_players %></p> -->

    <!-- <h3>Total Players: (<%= @game.signups.size %>/<%= @game.number_of_players %>)</h3> -->
<!-- <div class="leave">
    <% @game.signups.each do |signup| %>
      <div class='small-12 columns'>
        <div class='small-2 columns' style="font-size: 20px">

          <%=link_to signup.user.username, user_path(signup.user) %></div>
          <% if current_user == signup.user && current_user != @game.creator %>
            <div class='small-5 columns'><%= button_to 'Leave Game', game_signup_path(@game, signup), data: {confirm: "Are you sure you want to leave this game?"},  method: :delete, id: 'button' %></div>
          <% elsif current_user.id == @game.creator %>
            <div class='small-5 columns'><%= button_to 'Remove Player', game_signup_path(@game, signup), method: :delete, id: 'button' %></div>
          <% end %>
        </div>
    <% end %>
  </div> -->

<!-- <div class="request">
    <%= form_for [@game, @request] do |f| %>
    <%= f.text_field :body, placeholder: "Please tell us why you'd like to join", id: 'field' %>
    <%= f.submit value:'Request to Join', id: 'button' %>
    <% end %>
  </div>
  </p>
  <% if current_user && (Signup.where(user: current_user, game: @game) == []) && (Request.where(user: current_user, game: @game) == []) %>
  <% end %>
  <% if (Request.where(user: current_user, game: @game) != []) %>
    <div class='large-4 columns medium-2 columns small-6 columns float-right'>
      <% @request = Request.where(user: current_user, game: @game).first %>
      <%= button_to 'Delete Request', game_request_path(@game, @request), method: :delete, data: { confirm: "Are you sure?" }, id: 'button' %>
    </div>
  <% end %>
</div> -->

<!-- <div class='small-12 columns medium-4 columns large-4 columns float-right'>
  <div id='background' class='small-12 columns medium-11 columns float-right'>

    <% if current_user.id == @game.creator %>
      <h3>Requests:</h3>
      <% if @game.requests == [] %>
        No new requests.
      <% end %>
      <% @game.requests.each do |request| %>
        <%= request.user.username %>:
        <br /><%= request.body %>
        <%= form_for [@game, @signup] do |f| %>
          <%= f.hidden_field :user_id, value: request.user.id %>
          <%= f.submit(value="Add Player", id: 'special') %>
        <% end %>
        <%= button_to 'Deny', game_request_path(@game, request), method: :delete, id: 'special' %>
      <% end %>
    <% end %>

    <% if current_user.id == @game.creator %>
    <hr />
      <h3>Add Player to Game Manually:</h3>
        <%= form_for [@game, @signup] do |f| %>
        <%= f.label :user, value: 'Username of Player:' %>
        <%= f.text_field :user %>
        <%= f.submit(value='Add Player', id: 'special') %>
        <% end %>
    <% end %>

    <% if current_user.id == @game.creator %>
    <hr />
    <% end %>


    <h3>Your Games:</h3>
      <% if current_user.games == [] %>
        You have no games!
      <% end %>
      <% current_user.games.each do |game| %>
        <p>
          <% if (game.date > Time.zone.now + 1.day) %>
            <%= link_to game.title, game_path(game.id) %>: Role -
          <% if @game.creator == current_user.id %>
            Host
          <% else %>
            Player
          <% end %>
          <% end %>
        </p>
      <% end %>

      <% if (current_user.id == @game.creator) %>
      <div id="edit_link">
        <div class='large-12 columns medium-12 columns small-12 columns'>
          <%= link_to 'Edit Current Game', edit_game_path(@game), id: 'button', class: 'text-center' %>
        </div>
      </div>
      <% end %>
      <hr />
  </div>
</div> -->

  <div id="app"></div>

  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_JAVASCRIPT_KEY'] %>"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.4/underscore-min.js"></script>

  <script type="text/javascript">
    var address = '<%= @game.address %>';

    var map = new google.maps.Map(document.getElementById('map'), {
      mapTypeId: google.maps.MapTypeId.roadmap,
      zoom: 15
    });

    var geocoder = new google.maps.Geocoder();

    geocoder.geocode({
      'address': address
    },

    function(results, status) {
      if(status == google.maps.GeocoderStatus.OK) {
        new google.maps.Marker({
          position: results[0].geometry.location,
          map: map
        });
        map.setCenter(results[0].geometry.location);
      }
    });
  </script>
</div>