config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { confirmations: 'confirmations' }

  root 'home#index'

  resources :users do
    resources :bio, only: [:edit]
  end

  resources :games do
    resources :signups, only: [:create, :destroy]
    resources :requests, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :donate
  resources :about
  resources :comments
  resources :map, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :games, only: [:index, :new, :create, :show, :destroy]
      resources :users
      resources :comments, only: [:index, :new, :create]
      resources :nearmegames
    end
  end

  resources :conversations do
    resources :messages
  end

end

app/controllers/map_controller.rb
require 'gmaps4rails'

class MapController < ApplicationController

  def index
    @user = current_user
    @games = Game.where.not(lat: nil).where.not(lat: 0).where.not(lat: 1).where("date > ?", Time.zone.now - 1.day)
    @unlisted = Game.where(lat: nil)
    @unlisted += Game.where(lat: 1)
    @hash = Gmaps4rails.build_markers(@games) do |game, marker|
      marker.lat game.lat
      marker.lng game.lng
      marker.title game.title
      marker.infowindow "<h6><a href='/games/" + game.id.to_s + "'>" + game.title + "</a></h6><p>Address: " + game.address + "<br/>Description: " + game.gametype + "</br>Date: " + game.date + "<br>Time: " + game.time + "</p>"
    end
  end
end

app/views/map/index.html.erb
<div class='row'>
  <div class='columns small-12 text-center'>
    <h3> Game Portal </h3>
    <hr width='50%'/>
  </div>
</div>

<!-- <div id='mapbackground' class='column small-12'>
  <div class='columns small-12 text-center'>
    <h3> Game Portal </h3>
    <hr />
  </div> -->

<div class='row'>
  <div class='columns small-12 medium-6 text-center'>
    <div id="map" style='width: 100%; height: 400px;'></div>
  </div>
  <div class='columns small-12 medium-6 text-center recent-games--box'>
    <h4>Recently Added Games</h4>
    <div>
      <% Game.order(id: :desc).limit(5).each do |g| %>
        <%= link_to g.title, game_path(g) %> | <%= "#{g.gametype}" %> | <%= "#{g.address}" %>
      </br>
      </br>
      <% end %>
    </div>

    <!-- SEARCH BAR FOR GAMES -->
    <%= form_tag(games_path, :method => "get") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Games"%>
      <%= submit_tag "Search", :name => nil, class: 'button' %>
    <% end %>

    <%= button_to 'List a New Game', new_game_path, method: :get, class: 'button' %>
    <%= form_tag(games_path, :method => "get") %>
  </div>
</div>

<!-- <div id = 'maptile' class='columns small-8'>
  <div id="map" class='' style='width: 100%; height: 400px; '></div>
    <div id='buttons' class='column small 12'>
      <div class='medium-6 columns medium-offset-4 columns'>
        <div class="cluster">
          <%= form_tag(games_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Games", class: "search-bar"%>
            <%= submit_tag "Search", :name => nil, class:"button save-form" %>
            <% end %>
          <%= button_to 'List a New Game', new_game_path, method: :get, class:"button save-form" %>
          <%= form_tag(games_path, :method => "get") %>
        </div>
      </div>
    </div>
  </div> -->

<!-- <div id="gametile" class='small-4 columns'>
<h4>Recently Added Games</h4>
  <div id ="gametile_inner">
    <% Game.order(id: :desc).limit(4).each do |g| %>
      <%= link_to g.title, game_path(g) %>
    </br>
      <%= "#{g.gametype}" %>
    </br>
      <%= "#{g.address}" %>
    </br>
      <% end %>
  </div>
</div>
</div> -->

<!-- GOOGLE MAPS API SCRIPT -->
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_JAVASCRIPT_KEY'] %>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.4/underscore-min.js"></script>
<script type='text/javascript'>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(8);
  });
  function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude,
    infowindow: 'Your position'
  });
    handler.map.centerOn(marker);
    handler.getMap().setZoom(8);
  }
</script>